# Previsão de demanda

importação das bibliotecas

In [32]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in ./.venv/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [33]:
import pandas as pd 
import matplotlib as pyplot
import numpy as np
from sklearn.metrics import mean_absolute_error

Carregando os 4 arquivos

In [34]:
produtos = pd.read_csv('./1-lh_nautical_csv/products.csv')
variantes_produtos = pd.read_csv('./1-lh_nautical_csv/product_variants.csv')
pedidos = pd.read_csv('./1-lh_nautical_csv/orders.csv')
itens_pedido = pd.read_csv('./1-lh_nautical_csv/order_items.csv')

Unificar Datasets

In [35]:
# primeiro preciso achar as colunas comum entre eles
print(produtos.columns)
print(variantes_produtos.columns)
print(pedidos.columns)
print(itens_pedido.columns)

Index(['id', 'name', 'description', 'brand_id', 'category_id', 'ncm_code',
       'unit_of_measure', 'is_active', 'created_at', 'updated_at'],
      dtype='str')
Index(['id', 'product_id', 'sku', 'barcode_ean', 'sale_price', 'cost_price',
       'weight_kg', 'icms_rate', 'ipi_rate', 'is_active', 'created_at',
       'updated_at'],
      dtype='str')
Index(['id', 'order_number', 'channel', 'customer_id', 'salesperson_id',
       'location_id', 'status', 'subtotal', 'discount_amount', 'total',
       'placed_at', 'created_at', 'updated_at'],
      dtype='str')
Index(['id', 'order_id', 'product_variant_id', 'quantity', 'unit_price',
       'icms_rate', 'ipi_rate', 'line_total'],
      dtype='str')

In [36]:
arq_1 = pd.merge(
    produtos,
    variantes_produtos,
    left_on='id',
    right_on='product_id',
    suffixes=('_produto', '_variante')
)

arq_2 = pd.merge(
    arq_1,
    itens_pedido,
    left_on='id_variante',
    right_on='product_variant_id'
)

arq_final = pd.merge(
    arq_2,
    pedidos,
    left_on='order_id',
    right_on='id'
)

In [37]:
arq_final.head()

,id_produto,name,description,brand_id,category_id,ncm_code,unit_of_measure,is_active_produto,created_at_produto,updated_at_produto,...,customer_id,salesperson_id,location_id,status,subtotal,discount_amount,total,placed_at,created_at,updated_at
0,1,Motor de Popa 6014,Motor de popa 4 tempos para embarcações de lazer,9,9,50675645,UN,True,2023-06-07 05:32:02,2025-06-05 20:11:50,...,673,NaN,1,paid,39112.63,0.00,39112.63,2026-12-25 03:59:07,2026-12-25 03:59:07,2026-12-25 03:59:07
1,1,Motor de Popa 6014,Motor de popa 4 tempos para embarcações de lazer,9,9,50675645,UN,True,2023-06-07 05:32:02,2025-06-05 20:11:50,...,632,9.0,6,confirmed,31056.26,931.69,30124.57,2026-12-02 14:16:17,2026-12-02 14:16:17,2026-12-02 14:16:17
2,1,Motor de Popa 6014,Motor de popa 4 tempos para embarcações de lazer,9,9,50675645,UN,True,2023-06-07 05:32:02,2025-06-05 20:11:50,...,1230,NaN,6,paid,19558.96,0.00,19558.96,2025-05-18 06:07:52,2025-05-18 06:07:52,2025-05-18 06:07:52
3,1,Motor de Popa 6014,Motor de popa 4 tempos para embarcações de lazer,9,9,50675645,UN,True,2023-06-07 05:32:02,2025-06-05 20:11:50,...,1082,9.0,2,paid,26210.86,0.00,26210.86,2025-12-08 00:03:25,2025-12-08 00:03:25,2025-12-08 00:03:25
4,1,Motor de Popa 6014,Motor de popa 4 tempos para embarcações de lazer,9,9,50675645,UN,True,2023-06-07 05:32:02,2025-06-05 20:11:50,...,1656,6.0,3,confirmed,2452.69,0.00,2452.69,2025-04-23 03:34:47,2025-04-23 03:34:47,2025-04-23 03:34:47

Filtrar "Bússola de Bordo 702"

In [38]:
bussola = arq_final[arq_final['name'] == "Bússola de Bordo 702"].copy()
bussola.head()

,id_produto,name,description,brand_id,category_id,ncm_code,unit_of_measure,is_active_produto,created_at_produto,updated_at_produto,...,customer_id,salesperson_id,location_id,status,subtotal,discount_amount,total,placed_at,created_at,updated_at
21302,74,Bússola de Bordo 702,Bússola magnética líquida com iluminação,12,8,18607512,UN,True,2025-01-27 17:41:23,2025-04-09 17:31:25,...,780,NaN,2,cancelled,62090.37,0.00,62090.37,2022-04-01 07:44:41,2022-04-01 07:44:41,2022-04-01 07:44:41
21303,74,Bússola de Bordo 702,Bússola magnética líquida com iluminação,12,8,18607512,UN,True,2025-01-27 17:41:23,2025-04-09 17:31:25,...,1012,9.0,6,paid,13755.20,1513.07,12242.13,2023-03-07 03:00:18,2023-03-07 03:00:18,2023-03-07 03:00:18
21304,74,Bússola de Bordo 702,Bússola magnética líquida com iluminação,12,8,18607512,UN,True,2025-01-27 17:41:23,2025-04-09 17:31:25,...,1834,NaN,5,confirmed,11658.87,0.00,11658.87,2024-06-20 11:12:42,2024-06-20 11:12:42,2024-06-20 11:12:42
21305,74,Bússola de Bordo 702,Bússola magnética líquida com iluminação,12,8,18607512,UN,True,2025-01-27 17:41:23,2025-04-09 17:31:25,...,765,9.0,5,confirmed,45828.79,4582.88,41245.91,2023-04-27 03:56:27,2023-04-27 03:56:27,2023-04-27 03:56:27
21306,74,Bússola de Bordo 702,Bússola magnética líquida com iluminação,12,8,18607512,UN,True,2025-01-27 17:41:23,2025-04-09 17:31:25,...,1357,NaN,4,paid,37669.06,0.00,37669.06,2025-03-04 18:05:26,2025-03-04 18:05:26,2025-03-04 18:05:26

In [39]:
print(bussola.shape)

(472, 43)

In [40]:
# conferindo as datas 

bussola['placed_at'].min(), bussola['placed_at'].max()

('2020-01-03 22:58:57', '2026-12-31 21:59:40')

In [41]:
# como a datas no futuro vamos tratar

bussola = bussola[
    bussola['placed_at'] <= '2026-03-31'
].copy()

Criar vendas mensais

In [42]:
print(bussola['placed_at'].dtype) 
# tem que ser data

str

In [43]:
bussola['placed_at'] = pd.to_datetime(bussola['placed_at'])

In [44]:
vendas_mensais = (
    bussola.groupby(pd.Grouper(key = 'placed_at', freq = 'MS'))['quantity']
    .sum().reset_index()
)

vendas_mensais

    placed_at  quantity
0  2020-01-01        31
1  2020-02-01        16
2  2020-03-01        17
3  2020-04-01        32
4  2020-05-01         5
..        ...       ...
70 2025-11-01        60
71 2025-12-01        22
72 2026-01-01        79
73 2026-02-01        68
74 2026-03-01        60

[75 rows x 2 columns]

In [48]:
# verificando vendas mensais

print(vendas_mensais['placed_at'].min())
print(vendas_mensais['placed_at'].max())
print(len(vendas_mensais['placed_at']))

2020-01-01 00:00:00
2026-03-01 00:00:00
75

Separar treino e teste

In [50]:
treino = vendas_mensais[
    vendas_mensais['placed_at'] <= '2025-12-31'
].copy()
teste = vendas_mensais[
    (vendas_mensais['placed_at'] >= '2026-01-01') &
    (vendas_mensais['placed_at'] < '2026-03-31')
]

In [51]:
print("Treino: ")
print(treino)
print("Teste: ")
print(teste)

Treino:
    placed_at  quantity
0  2020-01-01        31
1  2020-02-01        16
2  2020-03-01        17
3  2020-04-01        32
4  2020-05-01         5
..        ...       ...
67 2025-08-01        23
68 2025-09-01        31
69 2025-10-01        34
70 2025-11-01        60
71 2025-12-01        22

[72 rows x 2 columns]
Teste:
    placed_at  quantity
72 2026-01-01        79
73 2026-02-01        68
74 2026-03-01        60

Calcular média movel em três meses

In [53]:
treino['previsao'] = (
    treino['quantity'].rolling(window = 3).mean().shift(1)
)

treino.head(10)

   placed_at  quantity   previsao
0 2020-01-01        31        NaN
1 2020-02-01        16        NaN
2 2020-03-01        17        NaN
3 2020-04-01        32  21.333333
4 2020-05-01         5  21.666667
5 2020-06-01         8  18.000000
6 2020-07-01         4  15.000000
7 2020-08-01         9   5.666667
8 2020-09-01        16   7.000000
9 2020-10-01         0   9.666667

In [56]:
# rolling pega os três meses e shift impede que a quantidade do proprio mes entre na previsão
vendas_mensais['media_3'] =(
    vendas_mensais['quantity'].rolling(window = 3).mean().shift(1) 
)

In [55]:
treino.tail()

    placed_at  quantity   previsao
67 2025-08-01        23  20.000000
68 2025-09-01        31  19.666667
69 2025-10-01        34  24.333333
70 2025-11-01        60  29.333333
71 2025-12-01        22  41.666667

Gerar Previsões para Jan/Fev/Mar de 2026

In [60]:
teste_previsao = vendas_mensais[
    (vendas_mensais['placed_at'] >= '2026-01-01') &
    (vendas_mensais['placed_at'] < '2026-03-31')    
].copy()
print(teste_previsao)

    placed_at  quantity    media_3
72 2026-01-01        79  38.666667
73 2026-02-01        68  53.666667
74 2026-03-01        60  56.333333

Calcular MAE 'Erro quadrático médio'

In [61]:
mae = mean_absolute_error(teste_previsao['quantity'], teste_previsao['media_3'])
print(mae)

19.444444444444446

ou seja, aproximadamente 19 unidades por mês

# Responda objetivamente:
     a. O baseline é adequado para esse produto?
     b. Cite uma limitação desse método.

a) Diria que é razoável porque o MAE indica aproximadamente um erro de 19.33 unidades o que é considerável.
    Aleḿ disso a média móvel bão consegue acompanhar bem um aumento de pico como foi em janeiro de 2026 

    
b) A média móvel não pega tendências ou sazonalidades o que é essencial para previsão de uma serie temporal, por isso que
quando a um pico de demanda o modelo fica prejudicado